packages:
  - packages/*

forceLegacyDeploy: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild

onlyBuiltDependencies:
  - bcrypt
  - better-sqlite3
  - msgpackr-extract
  - vue-demi
