"""Analysis tool handlers: validate input, call domain services, return results."""

from __future__ import annotations

from ..analysis_graph import GraphDatasetInput
from ..analysis_profile import ProfileDatasetInput
from ..artifact_service import (
    RegisterArtifactInput,
)
from ..storage.models import (
    ArtifactKind,
)
from ..llm.tool_protocol import (
    ToolExecutionContext,
    ToolSuccess,
)
from .tool_inputs import (
    AnalysisGraphInput,
    AnalysisProfileInput,
)
from ._tool_common import _raise_if_cancelled


class AnalysisTools:
    def __init__(
        self,
        *,
        dataset_service,
        artifact_service,
        analysis_profile_service,
        analysis_graph_service,
        ml_service,
    ) -> None:
        self._dataset_service = dataset_service
        self._artifact_service = artifact_service
        self._analysis_profile_service = analysis_profile_service
        self._analysis_graph_service = analysis_graph_service
        self._ml_service = ml_service

    def _analysis_graph(
        self,
        input_data: AnalysisGraphInput,
        context: ToolExecutionContext,
    ) -> ToolSuccess:
        _raise_if_cancelled(self._ml_service, context)
        dataset = self._dataset_service.get_dataset(input_data.dataset_id)
        raw_wordcloud_spec = (
            input_data.wordcloud_spec.model_dump(exclude_none=True)
            if input_data.wordcloud_spec is not None
            else None
        )
        graph_result = self._analysis_graph_service.graph_dataset(
            GraphDatasetInput(
                source_path=dataset.source_path,
                dataset_name=dataset.name,
                spec=input_data.spec,
                wordcloud_spec=raw_wordcloud_spec,
            )
        )
        graph_metadata = graph_result.graph_metadata
        default_title = f"{dataset.name} graph"
        title = str(graph_metadata.get("title") or default_title).strip() or default_title
        spec_format = str(graph_metadata.get("spec_format") or "graph")
        artifact = self._artifact_service.register_artifact(
            RegisterArtifactInput(
                kind=ArtifactKind.IMAGE,
                title=title,
                absolute_path=graph_result.output_path,
                mime_type="image/svg+xml",
                summary=f"Graph generated by analysis.graph ({spec_format}).",
                preview_payload=graph_metadata,
                metadata_payload={
                    "dataset_id": dataset.id,
                    "analysis_graph": graph_metadata,
                },
            )
        )
        payload = {
            "dataset_id": dataset.id,
            "artifact_id": artifact.id,
            "graph": graph_metadata,
        }
        return ToolSuccess(value=payload)

    def _analysis_profile(
        self,
        input_data: AnalysisProfileInput,
        context: ToolExecutionContext,
    ) -> ToolSuccess:
        _raise_if_cancelled(self._ml_service, context)
        result = self._analysis_profile_service.profile_dataset(
            ProfileDatasetInput(
                dataset_id=input_data.dataset_id,
                field_limit=input_data.field_limit,
                numeric_summary_limit=input_data.numeric_summary_limit,
                correlation_column_limit=input_data.correlation_column_limit,
            )
        )
        return ToolSuccess(value=result.model_dump(mode="json"))
