from __future__ import annotations

import os
import pprint
import re
import subprocess
import sys
import tomllib
from pathlib import Path

from PyInstaller.__main__ import run as pyinstaller_run

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from xenix.release_config import ReleaseConfig


_BUILD_COMMIT_PATTERN = re.compile(r"^[0-9a-fA-F]{7,40}$")
_SEMVER_PATTERN = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:[-+][0-9A-Za-z.-]+)?$")


def _generated_build_info_path(project_root: Path) -> Path:
    return project_root / "src" / "xenix" / "_generated_build_info.py"


def _generated_release_config_path(project_root: Path) -> Path:
    return project_root / "src" / "xenix" / "_generated_release_config.py"


def _windows_version_info_path(project_root: Path) -> Path:
    return project_root / "build" / "xenix-version-info.txt"


def _validate_build_commit(value: str) -> str:
    commit = value.strip()
    if not _BUILD_COMMIT_PATTERN.fullmatch(commit):
        raise ValueError(f"Build commit must be a 7-40 character git hash, got {value!r}.")
    return commit.lower()


def _resolve_build_commit(project_root: Path) -> str:
    env_commit = os.environ.get("XENIX_BUILD_COMMIT")
    if env_commit:
        return _validate_build_commit(env_commit)

    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            cwd=project_root,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(
            "Unable to resolve git commit for packaged build. "
            "Run packaging from a git checkout or set XENIX_BUILD_COMMIT."
        ) from exc
    return _validate_build_commit(result.stdout)


def _resolve_app_version(project_root: Path) -> str:
    document = tomllib.loads((project_root / "pyproject.toml").read_text(encoding="utf-8"))
    version = str(document["project"]["version"]).strip()
    if not _SEMVER_PATTERN.fullmatch(version):
        raise ValueError(f"Project version must be SemVer, got {version!r}.")
    return version


def _write_generated_build_info(project_root: Path, app_version: str, build_commit: str) -> Path:
    build_info_path = _generated_build_info_path(project_root)
    build_info_path.parent.mkdir(parents=True, exist_ok=True)
    build_info_path.write_text(
        "\n".join(
            (
                "from __future__ import annotations",
                "",
                "# Generated by scripts/package_app.py. Do not commit this file.",
                f'APP_VERSION = "{app_version}"',
                f'BUILD_COMMIT = "{build_commit}"',
                "",
            )
        ),
        encoding="utf-8",
    )
    return build_info_path


def _write_windows_version_info(project_root: Path, app_version: str) -> Path:
    numeric = app_version.split("+", 1)[0].split("-", 1)[0]
    parts = tuple(int(part) for part in numeric.split("."))
    file_version = (*parts, 0)
    dotted = ".".join(str(part) for part in file_version)
    path = _windows_version_info_path(project_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""VSVersionInfo(
  ffi=FixedFileInfo(filevers={file_version!r}, prodvers={file_version!r}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[StringFileInfo([StringTable('040904B0', [
    StringStruct('CompanyName', 'Xenix'),
    StringStruct('FileDescription', 'Xenix'),
    StringStruct('FileVersion', '{dotted}'),
    StringStruct('InternalName', 'xenix'),
    StringStruct('OriginalFilename', 'xenix.exe'),
    StringStruct('ProductName', 'Xenix'),
    StringStruct('ProductVersion', '{app_version}')
  ])]), VarFileInfo([VarStruct('Translation', [1033, 1200])])]
)\n""",
        encoding="utf-8",
    )
    return path


def _remove_generated_build_info(project_root: Path) -> None:
    _generated_build_info_path(project_root).unlink(missing_ok=True)


def _write_generated_release_config(project_root: Path, config: ReleaseConfig) -> Path:
    path = _generated_release_config_path(project_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = pprint.pformat(config.model_dump(mode="python"), sort_dicts=True, width=100)
    path.write_text(
        "from __future__ import annotations\n\n"
        "# Generated by scripts/package_app.py. Do not commit this file.\n"
        f"RELEASE_CONFIG = {payload}\n",
        encoding="utf-8",
    )
    return path


def _remove_generated_release_config(project_root: Path) -> None:
    _generated_release_config_path(project_root).unlink(missing_ok=True)
    # Clean files produced by the superseded split configuration implementation.
    (project_root / "src" / "xenix" / "_generated_trial_llm.py").unlink(missing_ok=True)
    (project_root / "src" / "xenix" / "_generated_trial_lock.py").unlink(missing_ok=True)


def _generate_agent_skill_catalog(project_root: Path) -> None:
    subprocess.run(
        [sys.executable, str(project_root / "scripts" / "agent_skills.py"), "generate"],
        check=True,
        cwd=project_root,
    )


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    subprocess.run(
        [sys.executable, str(project_root / "scripts" / "compile_translations.py")],
        check=True,
        cwd=project_root,
    )
    _generate_agent_skill_catalog(project_root)
    build_commit = _resolve_build_commit(project_root)
    app_version = _resolve_app_version(project_root)
    release_config = ReleaseConfig.from_environment(
        os.environ,
        release_build=os.environ.get("XENIX_RELEASE_BUILD", "").strip() == "1",
        public_release_build=os.environ.get("XENIX_PUBLIC_RELEASE_BUILD", "").strip() == "1",
        build_commit=build_commit,
    )
    try:
        _write_generated_build_info(project_root, app_version, build_commit)
        _write_windows_version_info(project_root, app_version)
        _write_generated_release_config(project_root, release_config)
        print(f"Embedding app version: {app_version}")
        print(f"Embedding build commit: {build_commit}")
        if release_config.trial_llm_api_key:
            print("Embedding packaged trial LLM provider: enabled")
        else:
            print("Embedding packaged trial LLM provider: disabled")
        if release_config.trial_lock_days > 0:
            print(f"Embedding startup trial lock: {release_config.trial_lock_days} day(s)")
        else:
            print("Embedding startup trial lock: disabled")
        pyinstaller_run(
            [
                "--clean",
                "--noconfirm",
                str(project_root / "xenix.spec"),
            ]
        )
    finally:
        _remove_generated_build_info(project_root)
        _remove_generated_release_config(project_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
