from __future__ import annotations

import os
import re
import secrets
import subprocess
import sys
from pathlib import Path

from PyInstaller.__main__ import run as pyinstaller_run


_BUILD_COMMIT_PATTERN = re.compile(r"^[0-9a-fA-F]{7,40}$")


def _generated_build_info_path(project_root: Path) -> Path:
    return project_root / "src" / "xenix" / "_generated_build_info.py"


def _generated_trial_llm_path(project_root: Path) -> Path:
    return project_root / "src" / "xenix" / "_generated_trial_llm.py"


def _generated_trial_lock_path(project_root: Path) -> Path:
    return project_root / "src" / "xenix" / "_generated_trial_lock.py"


def _validate_build_commit(value: str) -> str:
    commit = value.strip()
    if not _BUILD_COMMIT_PATTERN.fullmatch(commit):
        raise ValueError(f"Build commit must be a 7-40 character git hash, got {value!r}.")
    return commit.lower()


def _resolve_build_commit(project_root: Path) -> str:
    env_commit = os.environ.get("XENIX_BUILD_COMMIT")
    if env_commit:
        return _validate_build_commit(env_commit)

    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            cwd=project_root,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(
            "Unable to resolve git commit for packaged build. "
            "Run packaging from a git checkout or set XENIX_BUILD_COMMIT."
        ) from exc
    return _validate_build_commit(result.stdout)


def _write_generated_build_info(project_root: Path, build_commit: str) -> Path:
    build_info_path = _generated_build_info_path(project_root)
    build_info_path.parent.mkdir(parents=True, exist_ok=True)
    build_info_path.write_text(
        "\n".join(
            (
                "from __future__ import annotations",
                "",
                "# Generated by scripts/package_app.py. Do not commit this file.",
                f'BUILD_COMMIT = "{build_commit}"',
                "",
            )
        ),
        encoding="utf-8",
    )
    return build_info_path


def _remove_generated_build_info(project_root: Path) -> None:
    _generated_build_info_path(project_root).unlink(missing_ok=True)


def _write_generated_trial_llm(project_root: Path) -> Path:
    trial_llm_path = _generated_trial_llm_path(project_root)
    trial_llm_path.parent.mkdir(parents=True, exist_ok=True)
    base_url = os.environ.get("XENIX_TRIAL_LLM_BASE_URL", "https://api.openai.com").strip()
    api_key = os.environ.get("XENIX_TRIAL_LLM_API_KEY", "")
    model = os.environ.get("XENIX_TRIAL_LLM_MODEL", "gpt-4o-mini").strip()
    trial_llm_path.write_text(
        "\n".join(
            (
                "from __future__ import annotations",
                "",
                "# Generated by scripts/package_app.py. Do not commit this file.",
                f"TRIAL_LLM_BASE_URL = {base_url!r}",
                f"TRIAL_LLM_API_KEY = {api_key!r}",
                f"TRIAL_LLM_MODEL = {model!r}",
                "",
            )
        ),
        encoding="utf-8",
    )
    return trial_llm_path


def _remove_generated_trial_llm(project_root: Path) -> None:
    _generated_trial_llm_path(project_root).unlink(missing_ok=True)


def _resolve_trial_lock_days() -> int:
    raw_days = os.environ.get("XENIX_TRIAL_LOCK_DAYS", "").strip()
    if not raw_days:
        return 0
    try:
        days = int(raw_days, 10)
    except ValueError as exc:
        raise ValueError("XENIX_TRIAL_LOCK_DAYS must be a non-negative integer.") from exc
    if days < 0:
        raise ValueError("XENIX_TRIAL_LOCK_DAYS must be a non-negative integer.")
    return days


def _write_generated_trial_lock(
    project_root: Path,
    build_commit: str,
    trial_lock_days: int | None = None,
) -> Path:
    trial_lock_path = _generated_trial_lock_path(project_root)
    trial_lock_path.parent.mkdir(parents=True, exist_ok=True)
    days = _resolve_trial_lock_days() if trial_lock_days is None else trial_lock_days
    state_secret = secrets.token_urlsafe(32) if days > 0 else ""
    trial_lock_path.write_text(
        "\n".join(
            (
                "from __future__ import annotations",
                "",
                "# Generated by scripts/package_app.py. Do not commit this file.",
                f"TRIAL_LOCK_DAYS = {days!r}",
                f"TRIAL_LOCK_STATE_SECRET = {state_secret!r}",
                f"TRIAL_LOCK_BUILD_ID = {build_commit!r}",
                "",
            )
        ),
        encoding="utf-8",
    )
    return trial_lock_path


def _remove_generated_trial_lock(project_root: Path) -> None:
    _generated_trial_lock_path(project_root).unlink(missing_ok=True)


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    subprocess.run(
        [sys.executable, str(project_root / "scripts" / "compile_translations.py")],
        check=True,
        cwd=project_root,
    )
    build_commit = _resolve_build_commit(project_root)
    trial_lock_days = _resolve_trial_lock_days()
    _write_generated_build_info(project_root, build_commit)
    _write_generated_trial_llm(project_root)
    _write_generated_trial_lock(project_root, build_commit, trial_lock_days)
    print(f"Embedding build commit: {build_commit}")
    if os.environ.get("XENIX_TRIAL_LLM_API_KEY"):
        print("Embedding packaged trial LLM provider: enabled")
    else:
        print("Embedding packaged trial LLM provider: disabled")
    if trial_lock_days > 0:
        print(f"Embedding startup trial lock: {trial_lock_days} day(s)")
    else:
        print("Embedding startup trial lock: disabled")
    try:
        pyinstaller_run(
            [
                "--clean",
                "--noconfirm",
                str(project_root / "xenix.spec"),
            ]
        )
    finally:
        _remove_generated_build_info(project_root)
        _remove_generated_trial_llm(project_root)
        _remove_generated_trial_lock(project_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
