name = "xenix-website-api"
main = "src/worker/index.ts"
compatibility_date = "2026-03-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "xenix"
database_id = "b8707e24-8451-46d5-8636-4fd860445fe3"
migrations_dir = "drizzle"
